use std::fs;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct ServerConfig {
    pub domain: String,
    pub aliases: Vec<String>,
    pub port: u16,
    pub tls_cert: Option<String>,
    pub tls_key: Option<String>,
    pub gemini_port: Option<u16>,
    pub gph_port: Option<u16>,
    pub compression: bool,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            domain: "localhost".to_string(),
            aliases: Vec::new(),
            port: 7070,
            tls_cert: None,
            tls_key: None,
            gemini_port: None,
            gph_port: None,
            compression: false,
        }
    }
}

impl ServerConfig {
    /// Returns true if the given host (from Host header) matches primary domain or any alias.
    pub fn is_known_host(&self, host: &str) -> bool {
        // Strip port if present
        let host = host.split(':').next().unwrap_or(host);
        host == self.domain || self.aliases.iter().any(|a| a == host)
    }

    /// Given a Host header, return the matching domain or fall back to the primary.
    pub fn resolve_domain(&self, host: Option<&str>) -> String {
        if let Some(h) = host {
            let h = h.split(':').next().unwrap_or(h);
            if self.aliases.iter().any(|a| a == h) {
                return h.to_string();
            }
        }
        self.domain.clone()
    }

    pub fn has_tls(&self) -> bool {
        self.tls_cert.is_some() && self.tls_key.is_some()
    }

    pub fn has_gemini(&self) -> bool {
        self.gemini_port.is_some() && self.has_tls()
    }

    pub fn has_gph(&self) -> bool {
        self.gph_port.is_some() && self.has_tls()
    }

    pub fn gemini_bind_addr(&self) -> Option<String> {
        self.gemini_port.map(|p| format!("0.0.0.0:{}", p))
    }

    pub fn gph_bind_addr(&self) -> Option<String> {
        self.gph_port.map(|p| format!("0.0.0.0:{}", p))
    }

    pub fn load() -> Self {
        Self::load_from(Path::new("burrow.conf"))
    }

    pub fn load_from(path: &Path) -> Self {
        if !path.exists() {
            return Self::default();
        }

        let content = fs::read_to_string(path).unwrap_or_default();
        let mut config = Self::default();

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(val) = line.strip_prefix("domain = ") {
                config.domain = val.trim().to_string();
            } else if let Some(val) = line.strip_prefix("port = ") {
                if let Ok(p) = val.trim().parse() {
                    config.port = p;
                }
            } else if let Some(val) = line.strip_prefix("tls_cert = ") {
                let path = val.trim().to_string();
                if !path.is_empty() {
                    config.tls_cert = Some(path);
                }
            } else if let Some(val) = line.strip_prefix("tls_key = ") {
                let path = val.trim().to_string();
                if !path.is_empty() {
                    config.tls_key = Some(path);
                }
            } else if let Some(val) = line.strip_prefix("gemini_port = ") {
                if let Ok(p) = val.trim().parse() {
                    config.gemini_port = Some(p);
                }
            } else if let Some(val) = line.strip_prefix("gph_port = ") {
                if let Ok(p) = val.trim().parse() {
                    config.gph_port = Some(p);
                }
            } else if let Some(val) = line.strip_prefix("compression = ") {
                config.compression = val.trim() == "true";
            } else if let Some(val) = line.strip_prefix("aliases = ") {
                config.aliases = val.split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
        }
        config
    }

    pub fn save(&self, path: &Path) {
        let content = format!(
            "# Burrow server configuration\n# Generated by: burrow server init\n\ndomain = {}\nport = {}\n",
            self.domain, self.port
        );
        fs::write(path, content).unwrap();
    }

    pub fn bind_addr(&self) -> String {
        format!("0.0.0.0:{}", self.port)
    }
}
