use std::fs;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct ServerConfig {
    pub domain: String,
    pub port: u16,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            domain: "localhost".to_string(),
            port: 7070,
        }
    }
}

impl ServerConfig {
    pub fn load() -> Self {
        let path = Path::new("burrow.conf");
        if !path.exists() {
            return Self::default();
        }

        let content = fs::read_to_string(path).unwrap_or_default();
        let mut config = Self::default();

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(val) = line.strip_prefix("domain = ") {
                config.domain = val.trim().to_string();
            } else if let Some(val) = line.strip_prefix("port = ") {
                if let Ok(p) = val.trim().parse() {
                    config.port = p;
                }
            }
        }
        config
    }

    pub fn save(&self, path: &Path) {
        let content = format!(
            "# Burrow server configuration\n# Generated by: burrow server init\n\ndomain = {}\nport = {}\n",
            self.domain, self.port
        );
        fs::write(path, content).unwrap();
    }

    pub fn bind_addr(&self) -> String {
        format!("127.0.0.1:{}", self.port)
    }
}
